### ISSUE TITLE
blacklist show

### ISSUE THREAD

**Issue by Luckygermany** [tibue99/ezcord#44]
### EzCord Version

Master Branch

### Version

2.4.1

### Bug Description

i wanted to see in the command the date when the user was banned, then i got an error and i used the blacklist show command from ezcord (the automatic one) and got the error there too. 

the dt is saved as timedelta

### Bug Traceback

```
the blacklist show command is not working:

AttributeError: 'str' object has no attribute 'date'
```

**Comment by tibue99** [comment]
Hey, unfortunately I had to change the type of the `dt` attribute in the blacklist database. You can fix this by changing the type to `TIMESTAMP` in your database or by deleting the database to automatically create the new one.

I'll put this in the patch notes for the next update.
