### ISSUE TITLE
Geister error mit SlashCommandGroups?

### ISSUE THREAD

**Issue by MauriceHandwerker** [tibue99/ezcord#45]
### EzCord Version

0.5.1

### Version

Pycord 2.4.1

### Bug Description

Hi wir arbeiten derzeit an der Implementation von Ezcord in unserem Bot. Wir benutzen ``SlashCommandGroups`` für einige unserer Commands. 

Das ist der Fehler in der Konsole : 
```log
[COG] Loaded 3 cogs
CogsFolder STARTED
[ERROR] Error in event on_ready 
Traceback (most recent call last):
  File "C:\Users\mauri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\mauri\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\ezcord\bot.py", line 389, in _check_cog_groups
    if cog.group not in self.cogs.keys():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: unhashable type: 'SlashCommandGroup'
[INFO] Bot is online with EzCord 0.5.1
```

Dies ist ein Beispiel der ``SlashCommandGroup`` aus unserem Code:
```py
import discord
from discord.ext import commands
from discord.commands import SlashCommandGroup
from LogManager import LogManager
from configManager import ConfigManager

class Config(commands.Cog):

    def __init__(self, BOT):
        self.BOT = BOT
        self.LogManager = LogManager()

    config = SlashCommandGroup("config")

    @config.command()
    @commands.guild_only()
    @commands.is_owner()
    async def view(self, ctx):
        await ctx.respond("comming soon")

def setup(BOT):
    BOT.add_cog(Config(BOT))
````

Es sieht aus als würde Ezcord ein problem mit der ``SlashCommandGroup`` haben. 
Das komische ist das alles so funktioniert wie es soll. Es ist einfach nur ein Fehler in der Konsole. Sonst ist alles gut.

### Bug Traceback

-

**Comment by tibue99** [comment]
Hey, leider konnte ich den Bug mit dem oben angegebenen Code und einer normalen `main.py` Datei nicht reproduzieren. Könntest du einen minimalen Code bereitstellen, bei dem der Code auftritt?

**Comment by MauriceHandwerker** [comment]
# Ergebniss Nachforschungen bezüglich des ``on_ready event error``

Wir konnten den Fehler auf die ``Annoucenment`` Klasse zurück verfolgen. Hier haben wir die ``Config`` Klasse und ``Announcement`` Klasse verglichen und haben einen unterschied gefunden. 

config.py 
```py
import discord
from discord.ext import commands
from discord.commands import SlashCommandGroup
from LogManager import LogManager
from configManager import ConfigManager

class Config(commands.Cog):

    def __init__(self, BOT):
        self.BOT = BOT
        self.LogManager = LogManager()

    config = SlashCommandGroup("config")

    @config.command()
    @commands.guild_only()
    @commands.is_owner()
    async def view(self, ctx):
        await ctx.respond("comming soon")

def setup(BOT):
    BOT.add_cog(Config(BOT))
```

announcement.py 
```py
import discord
from discord.ext import commands
from discord.commands import SlashCommandGroup
from LogManager import LogManager
from configManager import ConfigManager

class Announcement(commands.Cog):

    def __init__(self, BOT):
        self.BOT = BOT
        self.LogManager = LogManager()

    group = SlashCommandGroup(name="announcement", description="")

    @group.command()
    @commands.guild_only()
    async def view(self, ctx: discord.ApplicationContext):
        if not ConfigManager.checkIfUserHasPermissions(guildid=ctx.guild.id, rank='admin', user_roles=ctx.author.roles):
            await ctx.respond(f'You dont have permissions to use this command!')
            return
        
        CONFIG = ConfigManager.GET_GuildConfig(ctx.guild.id)
        channel = commands.Bot.get_channel(self.BOT, CONFIG['services']['announcement']['channel'])

        await ctx.respond(f'Announcement Channel : {channel.mention}') 

def setup(BOT):
    BOT.add_cog(Announcement(BOT))
```

Hier ist uns aufgefallen das der Variablen name für die ``SlashCommandGroup`` in der ``config.py`` gleich mit dem namen der Gruppe ist allerdings dies nicht in der ``announcement.py`` zu finden ist. Hier wurde die Variable der ``SlashCommandGroup`` anders als der name der Gruppe genannt. In diesem fall ``group``. Wir haben als versuch die Variable umbenannt zu ``announcement`` also gleich wie der name der Gruppe. Darauf hin ist der Fehler verschwunden. 

Anscheinend wird der Veriablen name abgerufen und nicht der ``SlashCommandGroup`` name der Gruppe. 
Sollte mann den Fehler haben muss man also einfach nur die Variable und den Gruppen namen gleich setzen.

**Comment by tibue99** [comment]
Hey, danke für die Analyse! Der Error lag, wie ihr schon richtig erkannt habt, an dem Namen `group`. Grundsätzlich dürfen die Variablen zwar anders heißen als die Gruppe, jedoch gibt es bei `ezcord.Cog` auch ein `group` Attribut, um mehrere Cogs zu gruppieren. Der Error ist entstanden, weil EzCord das `group` Attribut der `SlashCommandGroup` fälschlicherweise als Cog-Attribut erkannt hat.

**Comment by MauriceHandwerker** [comment]
Ahh gut zu wissen. evtl. sollte man das in die Dokumentation hinzufügen.
