### ISSUE TITLE
'Bot' object has no attribute 'command_prefix'

### ISSUE THREAD

**Issue by rishicorp1** [tibue99/ezcord#60]
### EzCord Version

latest

### Version

latest

### Bug Description

this ezcord extentions bot object has no attribute called commandprefix

### Reproduction Steps

client = ezcord.Bot(command_prefix=Auth.COMMAND_PREFIX, intents=intents, auto_sync_commands=True)

### Expected Results

all simply started

### Actual Results

[ERROR] Error in event on_ready 
Traceback (most recent call last):
  File "C:\Users\rishi\Desktop\gannu_work\venv\Lib\site-packages\discord\client.py", line 378, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\rishi\Desktop\gannu_work\main.py", line 70, in on_ready
    await update_status()
  File "C:\Users\rishi\Desktop\gannu_work\main.py", line 38, in update_status
    f'{client.command_prefix} prefix',
       ^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Bot' object has no attribute 'command_prefix'

**Comment by tibue99** [comment]
Hey, `ezcord.Bot` does only support slash command by default. If you want to use prefix commands, use `ezcord.PrefixBot` as described [here](https://ezcord.readthedocs.io/en/latest/ezcord/bot.html).
