### ISSUE TITLE
Übersetzung

### ISSUE THREAD

**Issue by Nico4devv** [tibue99/ezcord#90]
### EzCord Version

0.7.2
### Version

dev  version  (2.6.1.dev157+gdb5b466a)

### Bug Description

![image](https://github.com/user-attachments/assets/c7406775-918c-40a5-a319-c5c7f05e6031)
**### ich hab mein discord acc auf de und es wird die erste msg auf de anzeigt aber denn auf die 2 msg nicht** 

### Reproduction Steps

wenn man sein discord auf de hat und es wird die embeds auf en anzeigt manchmal in englisch deutsch wie auf dem foto und wenn du deinen discord server auf de hast und dann klappt alles

### Minimal Reproducible Code

```Python
ticket:
  setup:
    ticket_setup_embed:
      title: "🎫 Ticket System"
      description: "Hier können Sie alle Einstellungen für das Ticket-System verwalten.\n\n"

    ticket_embed:
      title: "🛠️ Support"
      description: "Wähle eine Kategorie, um den Support zu kontaktieren."

localized_strings = {
    "de": load_file("./utils/lang/de.yaml"),
    "en": load_file("./utils/lang/en.yaml"),
}

ezcord.I18N(localized_strings, fallback_locale="en", prefer_user_locale=True)
```

### Expected Results

das unten in der embed auch eigentlich auf deutsch sein aber es wird die ganze Zeit auf englisch gesendet wie jedes ein embeds  von mir von die Übersetzung von ezcord.Tembed halt von alle embed wenn ich mein discord server auf de macht denn geht alles 

### Actual Results

![image](https://github.com/user-attachments/assets/ee08852b-96ab-4aed-a0ca-886bffd651b6)
es zeigt halt auf en und de an

**Comment by tibue99** [comment]
Hey, please provide the actual code that is needed to reproduce this issue.

**Comment by Nico4devv** [comment]
das Problem tritt auf wenn man zwei embeds untereinander schreibt das erste embed geht ohne probleme

**Comment by tibue99** [comment]
Please provide the code

**Comment by Nico4devv** [comment]
und noch dazu wenn sein server auf de macht denn gehts es auch wieder aber wenn man die  user Sprache hat denn gehts es nicht und ich glaube mal es ist noch dazu wichtig
        embed = ezcord.TEmbed(
            "ticket_setup_embed",
            color=COLOR,
        )
        await ctx.respond(embed=embed, view=settings(), ephemeral=True)

        channel_id = await db.get_channel(ctx.guild.id)
        if channel_id:
            ticket_channel = ctx.guild.get_channel(ctx.channel.id)
            if ticket_channel:
                embed = ezcord.TEmbed(
                    "ticket_embed",
                    color=COLOR,
                )
                await ticket_channel.send(embed=embed, view=settings())  i18n = ezcord.I18N(localized_strings, fallback_locale="en", prefer_user_locale=True)

**Comment by Nico4devv** [comment]
wenn du noch die yaml Datei brauchst dann schreib mir

**Comment by Nico4devv** [comment]
, es verwendet einfach immer die Serversprache, egal was man macht

**Comment by tibue99** [comment]
I can't reproduce the issue if you don't provide the full code. It's likely an issue with your code setup, if you need any support feel free to join the Discord server.
